# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8013d9632958fc0a6aca1fe30af2fc19eff15000d3a04fae01f84ffaf0afb787dbfb24de2a3ae42f0f2e24c79fab146658c60daff1e4804a7c8b3d78b6787add

test:
  secret_key_base: c0140ba8dd29bc6b30515ccd08a24d1271ff606a739992bac79d8222603b4b0819fd649c2feb221711e177001caae92d0ef979afd8c3b1942d0584186d34553b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
